### ISSUE TITLE
Flac loading is unreliable when compiled with optimization

### ISSUE THREAD

**Issue by Keithcat1** [synthizer/synthizer#10]
When I try to load the below file in a buffer, buffer.get_length_in_samples() returned 0, which is why I think it's not loading properly.
This doesn't work with the Python example, either.
It doesn't seem to crash, it just sits there and doesn't make any sound.
I thought there was a way to attach files to issues, but since I can't figure it out, here is the link to the file on Dropbox again.
[https://www.dropbox.com/s/uhk8m6ybxj0opqz/ball.flac?dl=0](https://www.dropbox.com/s/uhk8m6ybxj0opqz/ball.flac?dl=0)

**Comment by camlorn** [comment]
There's a browse button below the comment. I have no idea what the restrictions are on it.  I'll look as soon as I have the bandwidth.

**Comment by camlorn** [comment]
I think this is fixed in 0.6.0.  Can you confirm?

**Comment by Keithcat1** [comment]
Nope, still the same problem. I've upgraded to 0.6.0 and tried to attach the problematic file.

**Comment by Keithcat1** [comment]
There. My window wasn't maximized
[ball.zip](https://github.com/synthizer/synthizer/files/5011079/ball.zip)
.

**Comment by camlorn** [comment]
Huh. I've duplicated it.  It only happens against the version on Pypi, which of course means it's going to be something obscure C++. I will hopefully have news shortly.

**Comment by camlorn** [comment]
Something appears to be overrunning a buffer in a way that asan can't find in release builds only, which is breaking any and all flack files.  I'm not sure if it's us or dr_flac at this point, but slowly leaning toward dr_flac.  Ubsan can detect the overrun indirectly by flagging a bunch of expressions that suddenly start overflowing when this happens, but it's too far away from the cause to trace it back via that either.

Obviously all flac files not working reliably is basically the highest priority issue and effectively blocking feature development, but I can't give you a timeline on a fix.

**Comment by camlorn** [comment]
Filed this upstream with a minimal test case: https://github.com/mackron/dr_libs/issues/143

It looks like things break specifically in the case of Clang 10 on Windows.  MSVC won't do it.  Clang 10 on Linux won't do it.

I don't know the dr_flac codebase well enough to take the investigation further, so we'll see what they say.  Until then, use wav or mp3.

**Comment by camlorn** [comment]
I have pushed 0.6.1, which disables dr_flac SIMD support, as this appears to break under clang-cl.  Can you confirm whether this works for you?

**Comment by Keithcat1** [comment]
I can confirm that the files that weren't working before are playable now. Thanks!

**Comment by camlorn** [comment]
Ok. I'll leave this open until I figure out just what's up with dr_flac.  Might want you to test again in a week or two if you're willing.

**Comment by Keithcat1** [comment]
No problem. Thanks for looking into this.

**Comment by camlorn** [comment]
I've uploaded 0.6.2, which re-enables dr_flac simd with the potential fix from mackron/dr_libs#143.  Can you test this?  If it's good, we can probably close this for the time being.

**Comment by Keithcat1** [comment]
Both streaming and buffers worked fine for me with the latest, 0.6.2
